package org.okis.enums;

/**
 *
 * @author E020682
 */
public enum Category {
    
	BOND_PRICE("BOND_PRICE"),
	BOND_SPREAD_CURVE("BOND_SPREAD_CURVE"),
	CORRELATIONS_CORRELATION("CORRELATIONS_CORRELATION"),
	CREDIT_CURVE("CREDIT_CURVE"),
	CREDIT_SHEET("CREDIT_SHEET"),
	CREDIT_VOL_CURVE("CREDIT_VOL_CURVE"),
	FX_FUTURE("FXFUTURE"),
	FX_SMILE("FXSMILE"),
	FX_SPOT("FXSPOT"),
	FX_SWAP("FXSWAP"),
	FX_VOLATILITY("FXVOLATILITY"),
	GMP_IF_SABR_SKEW("GMP_IF_SABR_SKEW"),
	GMP_IR_CORREC_LGM("GMP_IR_CORREC_LGM"),
	GMP_IR_MEANREV_MATR("GMP_IR_MEANREV_MATR"),
	GMP_IR_SABR_SKEW("GMP_IR_SABR_SKEW"),
	GMP_IR_SABR_TENORS("GMP_IR_SABR_TENORS"),
	GMP_IR_MEANREV("GMP_IR_MEANREV"),
	RATES_CAP_FLOOR("RATES_CAP_FLOOR"),
	RATES_CAP_SMILE("RATES_CAP_SMILE"),
	RATES_CURVE("RATES_CURVE"),
	RATES_INFLATION("RATES_INFLATION"),
	RATES_INFLATION_CAP_SMILE("RATES_INFLATION_CAP_SMILE"),
	RATES_INFLATION_CAP_VOL("RATES_INFLATION_CAP_VOL"),
	RATES_SHEET("RATES_SHEET"),
	SECURITIES_PRICES("SECURITIES_PRICES"),
	SIGNATURES("SIGNATURES"),
	SIGNATURES_REQUIRED("SIGNATURES_REQUIRED"),
	SWAPTION_SMILE("SWAPTION_SMILE"),
	SWAPTION_VOLATILITY("SWAPTION_VOLATILITY");

	private final String dbName;

	private Category(String dbName) {
		this.dbName = dbName;
	}

	public String getDbName() {
		return dbName;
	}

	public static String getDbNameToCategory(final String dbName) {
		String name = null;
		for (Category value : Category.values()) {
			if (value.getDbName().equals(dbName)) {
				name = value.name();
				break;
			}
		}
		return name;
	}	
}
